export default [
    {
        title:"首页",
        icon:"home",
        key:"/admin/home"
    },
    {
        title:"商品",
        icon:"appstore",
        key:"/admin/goods",
        children:[
            {
                title:"分类管理",
                icon:"bars",
                key:"/admin/kinds",
            },
            {
                title:"商品管理",
                icon:"tool",
                key:"/admin/product",
            }
        ]
    },
    {
        title:"用户管理",
        icon:"user",
        key:"/admin/user"
    },
    {
        title:"角色管理",
        icon:"safety",
        key:"/admin/role"
    },
    {
        title:"图形图表",
        icon:"area-chart",
        key:"/admin/diagram",
        children:[
            {
                title:"柱形图",
                icon:"bar-chart",
                key:"/admin/barchart"
            },
            {
                title:"折线图",
                icon:"line-chart",
                key:"/admin/linechart"
            },
            {
                title:"饼图",
                icon:"pie-chart",
                key:"/admin/piechart"
            }
        ]
    }
]